#! /bin/sh

### BEGIN INIT INFO
# Provides:          ddns
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PROG=/usr/sbin/noip2

do_start()
{
	$PROG -c /etc/ddns.conf
}

do_stop()
{
	killall -q noip2
	sleep 1
	[ -n "$(pgrep noip2)" ] && {
		sleep 1
		kill -9 $(pgrep noip2)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
