#! /bin/sh

### BEGIN INIT INFO
# Provides:          failover
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PROG=/usr/sbin/failoverd

do_start()
{
	enabled=$(uci get network.detection.enabled)
	[ "$enabled" = "1" ] || return

	$PROG &
}

do_stop()
{
	killall -q failoverd
	sleep 1
	[ -n "$(pgrep failoverd)" ] && {
		sleep 1
		kill -9 $(pgrep -x failoverd)
	}

	uci -P /var/state/ set network.wan.link='none'
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 3
	;;
esac
