#! /bin/sh

### BEGIN INIT INFO
# Provides:          gps
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PROG=/usr/sbin/gpsd

do_start()
{
	local enabled server port tty interval devid mode

	enabled=$(uci get gps.conf.enabled)
	server=$(uci get gps.conf.server_addr)
	port=$(uci get gps.conf.servver_port)
	interval=$(uci get gps.conf.report_interval)
	
	[ "$enabled" = "0" ] && return
	$PROG ${server} ${port} ${interval} &
}

do_stop()
{
	killall -q gpsd
	sleep 1
	[ -n "$(pgrep gpsd)" ] && {
		sleep 1
		kill -9 $(pgrep gpsd)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:


