#! /bin/sh

### BEGIN INIT INFO
# Provides:          lte
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

START_PROG=/usr/sbin/start_diald
STOP_PROG=/usr/sbin/stop_diald

do_start()
{
	enabled=$(uci get system.system.lte_enabled)
	[ "$enabled" = "0" ] && return

	local proto lte_interface

	proto=$(uci get network.swan.proto)

	$START_PROG swan
}

do_stop()
{
	$STOP_PROG
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
