#! /bin/sh

### BEGIN INIT INFO
# Provides:          schedule
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
### END INIT INFO

PROG=/usr/sbin/scheduled

do_start()
{
	enabled=$(uci get system.scheduled.enabled)
	
	[ "$enabled" = "0" ] && return
	$PROG >/dev/null &
}

do_stop()
{
	killall -q scheduled
	sleep 1
	[ -n "$(pgrep scheduled)" ] && {
		sleep 1
		kill -9 $(pgrep scheduled)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:


