#! /bin/sh

PROG=/usr/sbin/dctd
BACNET_PROG=/usr/sbin/bacserv

do_start()
{
	local enabled hour_enabled day_enabled bacnet_enabled

	enabled=$(uci get dct.basic.enabled)
	[ "$enabled" = "1" ] || return

	$PROG >/dev/null &

	bacnet_enabled=$(uci get dct.bacnet.enabled)
	[ "$bacnet_enabled" = "1" ] || return

	$BACNET_PROG >/dev/null &
}

do_stop()
{
	killall -q dctd
	sleep 1
	[ -n "$(pgrep dctd)" ] && {
		sleep 1
		kill -9 $(pgrep dctd)
	}

	killall -q bacserv
	sleep 1
	[ -n "$(pgrep bacserv)" ] && {
		sleep 1
		kill -9 $(pgrep bacserv)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
