#! /bin/sh

PROG=/usr/local/bin/ttyd

do_start()
{
	local port interface

	port=$(uci get terminal.terminal.port)
    interface=$(uci get terminal.terminal.interface)

    if [ ! $port ]; then
        port=7681
    fi

    if [ ! $interface ]; then
        interface='br0'
    fi

    $PROG -p $port -i $interface /bin/login >/dev/null &
}

do_stop()
{
	killall -q ttyd
	sleep 1
	[ -n "$(pgrep ttyd)" ] && {
		sleep 1
		kill -9 $(pgrep ttyd)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
