#!/bin/sh
sect=$1
proto=$(uci get network.$1.proto)

if [ "$proto" = "3g" -o "$proto" = "lte" ]; then
	apn=$(uci get network.$1.apn)
	service=$(uci get network.$1.service)
	username=$(uci get network.$1.username)
	password=$(uci get network.$1.password)
	auth_type=$(uci get network.$1.auth_type)
	dialnumber=$(uci get network.$1.dialnumber)
	data_saving_mode=$(uci get network.$1.data_saving_mode)

	/usr/sbin/diald ${apn:+-a $apn} \
		-o $proto				\
		${service:+-n $service}  \
		${username:+-u $username} \
		${password:+-p $password} \
		${auth_type:+-s $auth_type} \
		${dialnumber:+-d $dialnumber} \
		${data_saving_mode:+-m $data_saving_mode} \
		-i $sect >/dev/null &
fi
