#! /bin/sh

PROG=/usr/sbin/noip2

do_start()
{
	$PROG -c /etc/ddns.conf
}

do_stop()
{
	killall -q noip2
	sleep 1
	[ -n "$(pgrep noip2)" ] && {
		sleep 1
		kill -9 $(pgrep noip2)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
