#! /bin/sh

PROG=/usr/sbin/gpsd

do_start()
{
	local enabled server port tty interval devid mode

	enabled=$(uci get gps.conf.enabled)
	server=$(uci get gps.conf.server_addr)
	port=$(uci get gps.conf.servver_port)
	interval=$(uci get gps.conf.report_interval)
	
	[ "$enabled" = "0" ] && return
	$PROG ${server} ${port} ${interval} &
}

do_stop()
{
	kill $(cat /var/run/gpsd.pid)
	sleep 1
	kill -9 $(cat /var/run/gpsd.pid)
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:


