#! /bin/sh

do_start()
{
	local enabled

        enabled=$(uci get loragw.loragw.type)
        [ "$enabled" = "1" ] || return


	/usr/sbin/lora_pkt_fwd -c /etc/global_conf.json &
}

do_stop()
{
	killall -q lora_pkt_fwd
	sleep 1
	[ -n "$(pgrep lora_pkt_fwd)" ] && {
		sleep 1
		kill -9 $(pgrep lora_pkt_fwd)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
