#! /bin/sh

PROG=/usr/sbin/failoverd

do_start()
{
	$PROG &
}

do_stop()
{
  killall -q failoverd
	sleep 1
	[ -n "$(pgrep failoverd)" ] && {
		sleep 1
		kill -9 $(pgrep failoverd)
	}
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
	exit 3
	;;
esac

:
